# Generated by Django 3.2.9 on 2021-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=50)),
                ('publishedData', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('pageCount', models.CharField(max_length=5)),
                ('selfLink', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
